import { NextPage } from 'next';
import Head from 'next/head';
import { About, Contact, Main, NavBar, Projects, Skills } from '@/components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Daiber | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <NavBar />
      <Main />
      <About />
      <Skills />
      <Projects />
      <Contact />
    </>
  );
};

export default Home;
